image: rust:slim-bookworm

stages:
    - test

testing:
    stage: test
    script:
        - apt-get update
        - apt-get -y install curl jq pkg-config libfreetype6-dev libfontconfig1-dev openssl
        - cargo test
        - ./install-llvm-cov
        - cargo llvm-cov --lib --json --ignore-filename-regex plotcolors > cov.json
        - ./coverage
    coverage: '/Total\:.*\%/'
