image: rust:slim-bookworm

stages:
    - test

testing:
    stage: test
    script:
        - cargo test
        - cargo +stable install cargo-llvm-cov --locked
        - cargo llvm-cov --lib --json > cov.json
        - ./coverage
    coverage: '/Total\:.*\%/'
